### PR TITLE
Example project

### PR DESCRIPTION
**Pull request by pepibumur**
### TODO :white_check_mark: 
- [x] CoreDataBasic Example
- [x] RealmBasic Example

### Bugs found
- [x] If you search and remove an object in the same operation for Realm the app crashes.

### CODE REVIEW

**Comment by sharpnk** [comment]
Nice work, but is core data example out of scope for this one?

**Comment by pepibumur** [comment]
Why do you think so @sharpnk

**Comment by sharpnk** [comment]
@pepibumur Oh never mind, sorry I think I had a little misunderstanding with the original pull request. I thought this pull request would have already included the core data example, but I guess it's still a work in progress.

**Comment by pepibumur** [comment]
Yes, exactly, it's still WIP, but it's almost done :)

**Pull request merged**
